name: publish

on:
  release:
    types: [published]

env:
  rust_toolchain: nightly

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup
        uses: pulse-loop/esp32-rust-action@v1
      
      - name: Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_REGISTRY_TOKEN }}