[build]
target = "riscv32imc-esp-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = ["-C", "default-linker-libraries"]
runner = "espflash flash --monitor -b 2000000 "

[env]
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"
ESP_IDF_VERSION = "v4.4.4"

ESP_IDF_GLOB_CONFIG_FILES_BASE = { value = ".", relative = true }
ESP_IDF_GLOB_CONFIG_FILES_1 = { value = "/partitions.csv" }

[unstable]
build-std = ["std", "panic_abort"]

[net]
git-fetch-with-cli = true
